kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: 力扣备份 # 定义流水线名称
steps:
  - name: 力扣备份
    image: harbor.wsh-study.com/public/ubuntu:20.0.4
    auth_config:
      username: admin
      password: admin123    
    commands:
      - ls   
      - pwd  